apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-practice-app
  namespace: gitops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gitops-practice-app
  template:
    metadata:
      labels:
        app: gitops-practice-app
    spec:
       containers:
         - name: gitops-app
           image: ssm0712/gitops-full-project-practice:5eb35ae6b8eab1505ee840fa6ee618f112f2c561
           ports:
           - containerPort: 3000
           resources:
             requests:
               cpu: 100m
               memory: 128Mi
             limits:
               cpu: 200m
               memory: 256Mi

              
