name: Gitops Full Practice

on:
  push:
    branches: [ "main" ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: |
        docker build -t ssm0712/gitops-full-project-practice:${{ github.sha }} .
        docker build -t ssm0712/gitops-full-project-practice:latest .
    
    - name: Login to Dockerhub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Push Docker Images
      run: |
        docker push ssm0712/gitops-full-project-practice:${{ github.sha }}
        docker push ssm0712/gitops-full-project-practice:latest

    - name: Update deployment
      run: |
        git config user.name "github-actions"
        git config user.email "github@gmail.com"
        git fetch origin main
        git reset --hard origin/main
        sed -i "s|image: .*|image: ssm0712/gitops-full-project-practice:${{ github.sha }}|" kubernetes/deployment.yaml
        git add kubernetes/deployment.yaml
        git commit -m "Update image to ${{ github.sha }}" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/sukhdeep07civil/gitops-full-project-practice.git HEAD:main
